#!/bin/bash

# Create and checkout a new branch
git checkout -b restructured

# Create new directories
mkdir -p Resources
mkdir -p Prompt_Patterns
mkdir -p Advanced_Data_Analysis

# Move and rename files to Resources
mv General_Resources/Additional_Readings.md Resources/additional_readings.md
mv General_Resources/Glossary.md Resources/glossary.md
mv General_Resources/Useful_Links.md Resources/useful_links.md
mv General_Resources/combined_libraries_data.csv Resources/combined_libraries_data.csv

# Move and rename files to Prompt_Patterns
mv Prompt_Engineering_for_ChatGPT/00_Prompt_Patterns.md Prompt_Patterns/prompt_patterns_overview.md
mv Prompt_Engineering_for_ChatGPT/01_Persona_Pattern.md Prompt_Patterns/persona_pattern.md
mv Prompt_Engineering_for_ChatGPT/02_Question_Refinement_Pattern.md Prompt_Patterns/question_refinement_pattern.md
mv Prompt_Engineering_for_ChatGPT/03_Cognitive_Verifier_Pattern.md Prompt_Patterns/cognitive_verifier_pattern.md
mv Prompt_Engineering_for_ChatGPT/04_Audience_Persona_Pattern.md Prompt_Patterns/audience_persona_pattern.md
mv Prompt_Engineering_for_ChatGPT/05_Flipped_Interaction_Pattern.md Prompt_Patterns/flipped_interaction_pattern.md
mv Prompt_Engineering_for_ChatGPT/06_Advanced_Prompting_Techniques.md Prompt_Patterns/advanced_prompting_techniques.md
mv Prompt_Engineering_for_ChatGPT/07_Game_Play_Pattern.md Prompt_Patterns/game_play_pattern.md
mv Prompt_Engineering_for_ChatGPT/08_Template_Pattern.md Prompt_Patterns/template_pattern.md
mv Prompt_Engineering_for_ChatGPT/09_Meta_Language_Creation_Pattern.md Prompt_Patterns/meta_language_creation_pattern.md
mv Prompt_Engineering_for_ChatGPT/10_Recipe_Pattern.md Prompt_Patterns/recipe_pattern.md
mv Prompt_Engineering_for_ChatGPT/11_Alternative_Approach_Pattern.md Prompt_Patterns/alternative_approach_pattern.md
mv Prompt_Engineering_for_ChatGPT/12_Fact_Check_List_Pattern.md Prompt_Patterns/fact_check_list_pattern.md
mv Prompt_Engineering_for_ChatGPT/Resources/References.md Prompt_Patterns/references.md

# Move and rename files to Advanced_Data_Analysis
mv ChatGPT_Advanced_Data_Analysis/Getting_Information_Into_Conversations.md Advanced_Data_Analysis/getting_information_into_conversations.md
mv ChatGPT_Advanced_Data_Analysis/Idea_Finder.md Advanced_Data_Analysis/idea_finder.md
mv ChatGPT_Advanced_Data_Analysis/document_modes.md Advanced_Data_Analysis/document_modes.md
mv ChatGPT_Advanced_Data_Analysis/manual_pattern.md Advanced_Data_Analysis/manual_pattern.md
mv ChatGPT_Advanced_Data_Analysis/try_again_pattern.md Advanced_Data_Analysis/try_again_pattern.md

# Remove empty directories
rmdir General_Resources
rmdir Prompt_Engineering_for_ChatGPT/Resources
rmdir Prompt_Engineering_for_ChatGPT
rmdir ChatGPT_Advanced_Data_Analysis

# Commit the changes
git add .
git commit -m "Restructure repository and unify file names"

echo "Repository restructuring and file renaming completed successfully on branch 'restructured'."